### ISSUE TITLE
question

### ISSUE THREAD

**Issue by SELECT-FROM** [OmicsML/awesome-molecule-protein-pretrain-papers#1]
Hello, I'm sorry for asking a question unrelated to this project. Could you please send me a copy of the scBERT pre training script

**Comment by SELECT-FROM** [comment]
@QiaolinLu

**Comment by QiaolinLu** [comment]
Hi, I wrote the script by myself instead of vanilla version. Could you provide your email please? I will send you later.

**Comment by SELECT-FROM** [comment]
> Hi, I wrote the script by myself instead of vanilla version. Could you provide your email please? I will send you later.

Thanks very much. My email is 2177671964@qq.com.
